[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python init_db.py"]

[start]
cmd = "cd src && gunicorn -c ../gunicorn.conf.py wsgi:app"

